apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: multi-component-application
    appstudio.openshift.io/component: devfile-go-sample-multi-component-example-main-kwpy
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-go-sample-multi-component-example-main-kwpy
  namespace: e2e-demo-waiz
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: devfile-go-sample-multi-component-example-main-kwpy
status:
  configuration:
    generatedName: ""
